---
# Each of these values can also be specified as environment variables.
# The environment variable will take precedence over the value in the config file.

# "LOG_LEVEL" can only be set as an environment variable.  Default LOG_LEVEL is WARNING.

tappecue_api_url: 'https://tappecue.babyvelociraptor.com'
tappecue_user: 'someuser@someuser.com'
tappecue_password: '123456'
check_probe_delay: 3
no_session_delay: 300
