---
services:
  tappecue-monitor:
    image: ghcr.io/frbird/tappecue-prometheus:latest
    # image: tappecue-monitor:latest
    ports:
      - 8000:8000
    # You can configure the app using environment variables or a config file.
    environment:
      - TAPPECUE_API_URL='https://tappecue.babyvelociraptor.com'
      - TAPPECUE_USER='someuser@someuser.com'
      - TAPPECUE_PASSWORD='123456'
      - CHECK_PROBE_DELAY=3
      - NO_SESSION_DELAY=300
      - VERIFY_SSL=False
      - LOG_LEVEL='info'
    # volumes:
    #   - ./config.yaml:/app/config.yaml
    restart: unless-stopped

# Add this to turn up a Grafana Agent container to scrape the metrics.
  # grafana-agent:
  #   image: grafana/agent:v0.27.0
  #   network_mode: host
  #   cap_add:
  #     - SYS_TIME
  #   pid: "host"
  #   volumes:
  #     - /tmp/agent:/etc/agent/data
  #     - /home/ubuntu/apps/grafana/config.yaml:/etc/agent/agent.yaml
  #     - "/:/host/root:ro,rslave"
  #     - "/sys:/host/sys:ro,rslave"
  #     - "/proc:/host/proc:ro,rslave"
  #     - /tmp/agent:/etc/agent
  #   restart: unless-stopped