name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.py'
      - '**/Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ContainerOperations }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        # context: .
        # file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/tappecue-monitor:latest
          ghcr.io/${{ github.repository }}/tappecue-monitor:${{ github.ref_name }}

# The code below has been replace by the code above.  Delete this code after testing the new code.
    # - name: Checkout code
    #   uses: actions/checkout@v4

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1

    # - name: Log in to the GitHub Container Registry
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.ContainerOperations }}

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag tappecue_monitor:latest

    # - name: Tag the Docker image
    #   run: docker tag tappecue_monitor:latest ghcr.io/${{ github.repository }}:latest

    # - name: Push the Docker image
    #   run: docker push ghcr.io/${{ github.repository }}:latest