name: Deploy Container

on:
  registry_package:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy container
        env:
          TAPPECUE_PASSWORD: ${{ secrets.TAPPECUE_PASSWORD }}
          TAPPECUE_USER: ${{ secrets.TAPPECUE_USER }}
          VERIFY_SSL: False
        run: |
          docker compose down
          docker compose pull
          docker compose up -d
