name: Deploy Container

on:
  push:
    branches: [ main ]
    paths:
      - '**/docker-compose.yaml'
  registry_package:
    types: [published]
    tags:
      - ghcr.io/frbird/tappecue-prometheus:latest
  workflow_dispatch:

concurrency:
  group: ${{ github.sha }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy container
        env:
          TAPPECUE_PASSWORD: ${{ secrets.TAPPECUE_PASSWORD }}
          TAPPECUE_USER: ${{ secrets.TAPPECUE_USER }}
        run: |
          docker compose down
          docker compose pull
          docker compose up -d
