name: Deploy Container

on:
  registry_package:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy container
        with:
          tappecue_password: ${{ secrets.TAPPECUE_PASSWORD }}
          tappecue_user: ${{ secrets.TAPPECUE_USER }}
        run: |
          docker compose down
          docker compose pull
          TAPPECUE_PASSWORD="$tappecue_password" \
          TAPPECUE_USER="$tappecue_user" \
          VERIFY_SSL=False \
          docker compose up -d
